//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedResource
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMORIA()
        {
            this.RENDELESEK = new HashSet<RENDELESEK>();
        }
    
        public decimal MEMORIA_ID { get; set; }
        public string TIPUSSZAM { get; set; }
        public string MEMORIATIPUS { get; set; }
        public decimal SEBESSEG { get; set; }
        public decimal KAPACITAS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RENDELESEK> RENDELESEK { get; set; }
    }
}
